
typedef enum ngap_proc_code_t {
    NGAP_AMFConfigurationUpdate = 0,
    NGAP_AMFStatusIndication,
    NGAP_CellTrafficTrace,
    NGAP_DeactivateTrace,
    NGAP_DownlinkNASTransport,
    NGAP_DownlinkNonUEAssociatedNRPPaTransport,
    NGAP_DownlinkRANConfigurationTransfer,
    NGAP_DownlinkRANStatusTransfer,
    NGAP_DownlinkUEAssociatedNRPPaTransport,
    NGAP_ErrorIndication,
    NGAP_HandoverCancel,
    NGAP_HandoverNotification,
    NGAP_HandoverPreparation,
    NGAP_HandoverResourceAllocation,
    NGAP_InitialContextSetup,
    NGAP_InitialUEMessage,
    NGAP_LocationReportingControl,
    NGAP_LocationReportingFailureIndication,
    NGAP_LocationReport,
    NGAP_NASNonDeliveryIndication,
    NGAP_NGReset,
    NGAP_NGSetup,
    NGAP_OverloadStart,
    NGAP_OverloadStop,
    NGAP_Paging,
    NGAP_PathSwitchRequest,
    NGAP_PDUSessionResourceModify,
    NGAP_PDUSessionResourceModifyIndication,
    NGAP_PDUSessionResourceRelease,
    NGAP_PDUSessionResourceSetup,
    NGAP_PDUSessionResourceNotify,
    NGAP_PrivateMessage,
    NGAP_PWSCancel,
    NGAP_PWSFailureIndication,
    NGAP_PWSRestartIndication,
    NGAP_RANConfigurationUpdate,
    NGAP_RerouteNASRequest,
    NGAP_RRCInactiveTransitionReport,
    NGAP_TraceFailureIndication,
    NGAP_TraceStart,
    NGAP_UEContextModification,
    NGAP_UEContextRelease,
    NGAP_UEContextReleaseRequest,
    NGAP_UERadioCapabilityCheck,
    NGAP_UERadioCapabilityInfoIndication,
    NGAP_UETNLABindingRelease,
    NGAP_UplinkNASTransport,
    NGAP_UplinkNonUEAssociatedNRPPaTransport,
    NGAP_UplinkRANConfigurationTransfer,
    NGAP_UplinkRANStatusTransfer,
    NGAP_UplinkUEAssociatedNRPPaTransport,
    NGAP_WriteReplaceWarning,
	NGAP_SecondaryRATDataUsageReport,
	NGAP_UplinkRIMInformationTransfer,
	NGAP_DownlinkRIMInformationTransfer,
	NGAP_RetrieveUEInformation,
	NGAP_UEInformationTransfer,
	NGAP_RANCPRelocationIndication,
	NGAP_UEContextResume,
	NGAP_UEContextSuspend,
	NGAP_UERadioCapabilityIDMapping,
	NGAP_HandoverSuccess,
	NGAP_UplinkRANEarlyStatusTransfer,
	NGAP_DownlinkRANEarlyStatusTransfer,
	NGAP_AMFCPRelocationIndication,
	NGAP_ConnectionEstablishmentIndication,
	NGAP_BroadcastSessionModification,
	NGAP_BroadcastSessionRelease,
	NGAP_BroadcastSessionSetup,
	NGAP_DistributionSetup,
	NGAP_DistributionRelease,
	NGAP_MulticastSessionActivation,
	NGAP_MulticastSessionDeactivation,
	NGAP_MulticastSessionUpdate,
	NGAP_MulticastGroupPaging,
	NGAP_BroadcastSessionReleaseRequired,		/* 75 */
	NGAP_ProcCodeUnknown
} ngap_proc_code_t;

/* ------------------------- libngapp.c --------------------------- */
const   char *NGAP_PROC_C_STR(int proc_code);
