#include "libngapp.h"

const char NGAP_PROC_CODE_STR[][128] = {
    "AMFConfigurationUpdate",
    "AMFStatusIndication",
    "CellTrafficTrace",
    "DeactivateTrace",
    "DownlinkNASTransport",
    "DownlinkNonUEAssociatedNRPPaTransport",
    "DownlinkRANConfigurationTransfer",
    "DownlinkRANStatusTransfer",
    "DownlinkUEAssociatedNRPPaTransport",
    "ErrorIndication",
    "HandoverCancel",
    "HandoverNotification",
    "HandoverPreparation",
    "HandoverResourceAllocation",
    "InitialContextSetup",
    "InitialUEMessage",
    "LocationReportingControl",
    "LocationReportingFailureIndication",
    "LocationReport",
    "NASNonDeliveryIndication",
    "NGReset",
    "NGSetup",
    "OverloadStart",
    "OverloadStop",
    "Paging",
    "PathSwitchRequest",
    "PDUSessionResourceModify",
    "PDUSessionResourceModifyIndication",
    "PDUSessionResourceRelease",
    "PDUSessionResourceSetup",
    "PDUSessionResourceNotify",
    "PrivateMessage",
    "PWSCancel",
    "PWSFailureIndication",
    "PWSRestartIndication",
    "RANConfigurationUpdate",
    "RerouteNASRequest",
    "RRCInactiveTransitionReport",
    "TraceFailureIndication",
    "TraceStart",
    "UEContextModification",
    "UEContextRelease",
    "UEContextReleaseRequest",
    "UERadioCapabilityCheck",
    "UERadioCapabilityInfoIndication",
    "UETNLABindingRelease",
    "UplinkNASTransport",
    "UplinkNonUEAssociatedNRPPaTransport",
    "UplinkRANConfigurationTransfer",
    "UplinkRANStatusTransfer",
    "UplinkUEAssociatedNRPPaTransport",
    "WriteReplaceWarning",
	"SecondaryRATDataUsageReport",
	"UplinkRIMInformationTransfer",
	"DownlinkRIMInformationTransfer",
	"RetrieveUEInformation",
	"UEInformationTransfer",
	"RANCPRelocationIndication",
	"UEContextResume",
	"UEContextSuspend",
	"UERadioCapabilityIDMapping",
	"HandoverSuccess",
	"UplinkRANEarlyStatusTransfer",
	"DownlinkRANEarlyStatusTransfer",
	"AMFCPRelocationIndication",
	"ConnectionEstablishmentIndication",
	"BroadcastSessionModification",
	"BroadcastSessionRelease",
	"BroadcastSessionSetup",
	"DistributionSetup",
	"DistributionRelease",
	"MulticastSessionActivation",
	"MulticastSessionDeactivation",
	"MulticastSessionUpdate",
	"MulticastGroupPaging",
	"BroadcastSessionReleaseRequired",
	"UnknownProcCode"
};

const char *NGAP_PROC_C_STR(int proc_code)
{
	if (proc_code < NGAP_AMFConfigurationUpdate || NGAP_BroadcastSessionReleaseRequired > 75) {
		return "UnknownCode";
	} else {
		return NGAP_PROC_CODE_STR[proc_code];
	}
}
